"""Centralized defaults for TimeSeries numerical behavior."""

TIME_DEDUP_ATOL = 1e-8
TIME_DEDUP_RTOL = 1e-7

APPROX_ABS_FLOOR = 1e-8
APPROX_REL_ERR_TARGET = 1e-3
APPROX_INITIAL_S = 1.0
APPROX_S_REDUCTION_FACTOR = 0.5
APPROX_MAX_REFIT_ATTEMPTS = 8
DIVISION_NEAR_ZERO_THRESHOLD = 1e-8
